#!/bin/bash
IFWIFI=wlan0

function start
{
    stop
    echo "running wpa_supplicant"
    wpa_supplicant -B -D nl80211 -i $IFWIFI  -c /etc/wpa_supplicant.conf -f /var/log/wpa_supplicant_network-switcher.log
    # wait for things to settle down
    sleep 2
    echo "running dhclient $IFWIFI"
    dhclient $IFWIFI
}

function stop
{
    echo "shutting down dhclient"
    killall -q dhclient
    echo "shutting down wpa_supplicant"
    wpa_cli terminate  > /dev/null 2>&1
}

function restart
{
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "$0 <start|stop|restart>"
esac
